### ISSUE TITLE
QueryTemplate nextPage calculation

### ISSUE THREAD

**Issue by YBCoding** [jottley/spring-social-salesforce#22]
Hi everyone,
Seems like calculation of nextPage in QueryTemplate is wrong.
It uses `api.getBaseUrl()` which send back `https://eu2.salesforce.com/services/data`.
The nextPageUrl is `pathOrToken = /services/data/v37.0/query/{Id}`
Following lines concatenates these two values wich results in 404 in practice :

https://github.com/jottley/spring-social-salesforce/blob/52c37961a76e78572ba715641590b0dbcd7422d3/src/main/java/org/springframework/social/salesforce/api/impl/QueryTemplate.java#L53

https://github.com/jottley/spring-social-salesforce/blob/52c37961a76e78572ba715641590b0dbcd7422d3/src/main/java/org/springframework/social/salesforce/api/impl/QueryTemplate.java#L55

A small test which can be added to QueryTemplateTest to see the problem.

```
    @Test
    public void validNextPageQuery() {
        mockServer.expect(requestTo("https://na7.salesforce.com/services/data/" + salesforce.apiOperations().getVersion() + "/query?q=SELECT+Id%2C+Name%2C+BillingCity+FROM+Account"))
                .andExpect(method(GET))
                .andRespond(withStatus(HttpStatus.OK).body(loadResource("query-simple.json")).headers(responseHeaders));
        mockServer.expect(requestTo("https://na7.salesforce.com/services/data/" + salesforce.apiOperations().getVersion() + "/query/01gD0000002HU6KIAW-2000"))
                .andExpect(method(GET))
                .andRespond(withStatus(HttpStatus.OK).body(loadResource("query-simple.json")).headers(responseHeaders));

        QueryResult result = salesforce.queryOperations().query("SELECT Id, Name, BillingCity FROM Account");
        String nextRecordsUrl = result.getNextRecordsUrl();
        assertEquals("/services/data/v37.0/query/01gD0000002HU6KIAW-2000", nextRecordsUrl);
        salesforce.queryOperations().nextPage(nextRecordsUrl);
    }
```

This could be solved by using `api.getInstanceUrl()` instead of `api.getBaseUrl()` but I do not know if it is the purpose of this property to be used in that way.
Should I do a PR ?

PS: I'm a bit new with github and opensource things, so bear with me if I do things wrong ^^.

**Comment by jottley** [comment]
You are correct in your understanding.  If you want to do a PR that would be great.

**Comment by jottley** [comment]
Actually unclosing since it was moved to develop....need to merge to master and then I can close it.

**Comment by jottley** [comment]
Added in 1.2.1.RELEASE
