### ISSUE TITLE
Return deleted items

### ISSUE THREAD

**Issue by Ksushik** [jottley/spring-social-salesforce#61]
Hello Jared

I use your library and before just query returned deleted items too, but with isDeleted=true
Now for the same functionality we should use queryAll
https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/dome_queryall.htm

Please add this functionality to your library

I've already added [pull request](https://github.com/jottley/spring-social-salesforce/pull/60), so it shouldn't take a lot of time

Thanks ahead

**Comment by jottley** [comment]
@Ksushik I've merged the PR and released it as part of 1.2.2.RELEASE. Thanks for your contribution.

**Comment by Ksushik** [comment]
Thank you very much, Jared!
